alter session set current_schema=bank;
SET heading OFF;

-- SELECT * FROM BANK_EMPLOYEE;

-- DESC BANK_EMPLOYEE;

--  Name					   Null?    Type
--  ----------------------------------------- -------- ----------------------------
--  BANK_EMP_ID				   NOT NULL NUMBER(5)
--  EMP_NAME				   NOT NULL VARCHAR2(40)
--  EMP_SEX				   NOT NULL CHAR(1)
--  DESIGNATION					    VARCHAR2(20)
--  MANAGER_ID					    NUMBER(6)

SELECT DESIGNATION,
COUNT(BANK_EMP_ID) AS EMP_COUNT
FROM BANK_EMPLOYEE
WHERE DESIGNATION NOT LIKE '%ATTENDER%'
GROUP BY DESIGNATION
ORDER BY COUNT(BANK_EMP_ID), DESIGNATION;

-- SELECT DESIGNATION, COUNT(BANK_EMP_ID) AS EMP_COUNT 
-- FROM BANK_EMPLOYEE 
-- WHERE DESIGNATION != 'ATTENDER' 
-- GROUP BY DESIGNATION
-- ORDER BY DESIGNATION ASC;
-- ORDER BY EMP_COUNT ASC;