SELECT CAR.RIDE_ID, CAR.FROM_LOCATION, CAR.TO_LOCATION, 
CAR.SEATS_LEFT, CAR.SEATS_TOTAL, CAR.RIDE_PROVIDER_ID, 
CAR.START_ON, CAR.ENDS_ON, CAR.ISSTARTED, CAR.ISFINISHED
FROM CARPOOLING.RIDE_USERS CR
JOIN CARPOOLING.USER_DETAILS CU
ON CR.USER_ID = CU.USER_ID
JOIN CARPOOLING.RIDE CAR
ON CAR.RIDE_ID = CR.RIDE_ID
WHERE FIRST_NAME = 'Krithik';