SELECT * FROM CARPOOLING.USER_DETAILS 
WHERE USER_ID IN (10005, 10003) 
ORDER BY USER_ID DESC;
-- SELECT COUNT(CR.RIDE_ID) AS TOTAL FROM CARPOOLING.RIDE_USERS CR
-- JOIN CARPOOLING.USER_DETAILS CU
-- ON CR.USER_ID = CU.USER_ID
-- JOIN CARPOOLING.RIDE CAR
-- ON CAR.RIDE_ID = CR.RIDE_ID
-- GROUP BY CR.RIDE_ID 
-- ORDER BY TOTAL DESC;

-- SELECT COUNT(RIDE_ID) FROM CARPOOLING.RIDE GROUP BY RIDE_ID;