SELECT * FROM USER_DETAILS WHERE USER_ID = 10018;

-- SELECT RIDE_ID FROM CARPOOLING.RIDE WHERE COUNT(RIDE_ID) IN 
-- (SELECT MAX(COUNT(RIDE_ID)) FROM CARPOOLING.RIDE GROUP BY RIDE_ID)
-- GROUP BY RIDE_ID ;