SELECT A.FIRST_NAME, A.CITY, COUNT(B.RIDE_ID) AS TOTAL_RIDES
FROM CARPOOLING.USER_DETAILS A, CARPOOLING.RIDE_USERS B 
WHERE A.USER_ID = B.USER_ID AND B.RIDE_ID IN 
(SELECT C.RIDE_ID FROM CARPOOLING.RIDE C
WHERE TO_CHAR(START_ON, 'MON') = 'DEC')
GROUP BY A.FIRST_NAME, A.CITY, A.USER_ID
ORDER BY A.USER_ID;