SELECT * FROM CARPOOLING.USER_DETAILS WHERE USER_ID IN (11006, 10016, 10017);
-- SELECT * FROM (SELECT 
-- UD.FIRST_NAME, COUNT(BR.RENTAL_ID) AS TOTAL 
-- FROM BOOK_RENTAL BR JOIN BOOKRENTAL.USER_DETAILS UD 
-- ON BR.USED_ID = UD.USER_ID
-- GROUP BY UD.FIRST_NAME
-- ORDER BY TOTAL DESC
-- )
-- WHERE ROWNUM < 4;

-- SELECT * FROM CARPOOLING.RIDE_USERS CR
-- JOIN CARPOOLING.USER_DETAILS CU
-- ON CR.USER_ID = CU.USER_ID 
-- WHERE RIDE_ID 
-- IN (SELECT FIRST_NAME, (FIRST_NAME) AS TOTAL 
-- FROM CARPOOLING.RIDE 
-- GROUP BY FIRST_NAME 
-- ORDER BY TOTAL DESC);

-- JOIN CARPOOLING.RIDE CAR
-- ON CAR.RIDE_ID = CR.RIDE_ID;