CREATE TABLE RIDE_USERS (
	RIDE_ID NUMBER(8),
    USER_ID NUMBER(8)
);

CREATE TABLE USER_DETAILS (
    USER_ID NUMBER(8),
    EMAIL_ID VARCHAR2(20),
    PASSWORD VARCHAR2(20),
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    CITY VARCHAR2(20),
    GENDER CHAR(1),
    PHONE_NO NUMBER(10)
);

CREATE TABLE RIDE (
	RIDE_ID NUMBER(5),
    FROM_LOCATION VARCHAR2(20),
    TO_LOCATION VARCHAR2(20),
    SEATS_LEFT NUMBER(2),
    SEATS_TOTAL NUMBER(2),
    RIDE_PROVIDER_ID NUMBER(8),
    START_ON TIMESTAMP(2),
    ENDS_ON TIMESTAMP(2),
    ISSTARTED VARCHAR2(4),
    ISFINISHED VARCHAR2(4)
);