alter session set current_schema=bank;
SET heading OFF;

-- SELECT * FROM BANK_FD_ACCOUNT;

-- DESC BANK_FD_ACCOUNT;

--  Name					   Null?    Type
--  ----------------------------------------- --------
--  ACCOUNT_NO				   NOT NULL NUMBER(15)
--  CUST_ID				   NOT NULL NUMBER(6)
--  START_DT				   NOT NULL DATE
--  FD_TERM_MNTH				   NOT NULL NUMBER(3)
--  INITIAL_AMT				   NOT NULL NUMBER(20,2)
--  ACC_STATUS					    VARCHAR2(10)

-- 5212340006	 1001	    45000 Active     26-SEP-05		 24
SELECT ACCOUNT_NO, CUST_ID, ROUND(INITIAL_AMT/100000,2) AS INITIALAMTIN_LAKHS, 
CASE
    WHEN INITIAL_AMT < 50000 THEN 'Low'
    WHEN INITIAL_AMT > 5000000 THEN 'High'
    ELSE 'Medium'
END AS AMOUNT_CATEGORY, 
START_DT,
ADD_MONTHS(START_DT, FD_TERM_MNTH) AS MATURITY_DATE
FROM BANK_FD_ACCOUNT 
WHERE UPPER(ACC_STATUS) = 'ACTIVE' and TO_CHAR(START_DT , 'YYYY') > 2004;